blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView
)
from . import views

urlpatterns = [
    path('', views.PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('book/<int:pk>/', views.book_detail, name='book-detail'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
    path('search/', views.SearchView.as_view(), name='blog-search'),
    # path('search/', views.book_search, name='blog-search'),
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('martor/', include('martor.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         user_views.PasswordResetConfirmViewEdit.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models import Q
from ckeditor.fields import RichTextField
from PIL import Image


class BookManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(title__icontains=query) |
                         Q(content__icontains=query) |
                         Q(author__icontains=query)
                        )
            qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return qs


class Post(models.Model):
    title = models.CharField(verbose_name='标题', max_length=100)
    # content = models.TextField()
    content = RichTextField(verbose_name='内容')
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

    def get_content(self):
        if len(self.content) > 1000:
            return self.content[:1000] + '...'
        return self.content


class Book(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.CharField(max_length=100)
    publisher = models.CharField(max_length=100)
    url = models.URLField()
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    objects = BookManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

comment/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from blog.models import Post


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.ForeignKey('Comment', null=True, related_name='replies', on_delete=models.CASCADE)
    created_on = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=False)
    body = models.TextField(verbose_name='内容')

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.author.username)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Post, Book
from itertools import chain
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from comment.forms import CommentForm
from django.contrib import messages
from comment.models import Comment
from random import randint


class SearchView(ListView):
    template_name = 'blog/search.html'
    paginate_by = 30
    count = 0

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['count'] = self.count or 0
        context['query'] = self.request.GET.get('q')
        return context

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q', None)

        if query is not None and query != "":
            blog_results = Book.objects.search(query)

            # combine querysets
            queryset_chain = chain(
                blog_results,
            )
            qs = sorted(queryset_chain,
                        key=lambda instance: instance.pk,
                        reverse=False)
            self.count = len(qs)  # since qs is actually a list
            return qs
        return Book.objects.none()  # just an empty queryset as default


def book_search(request):
    books_list = Book.objects.none()
    query = request.GET.get('q')
    print("this", query)
    if query:
        books_list = Book.objects.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(author__icontains=query)
        ).distinct()
    paginator = Paginator(books_list, 10)  # 6 posts per page
    page = request.GET.get('page')

    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)

    context = {
        'books': books
    }
    return render(request, "blog/search.html", context)


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})


def post_detail(request, pk):
    template_name = 'blog/post_detail.html'
    post = get_object_or_404(Post, pk=pk)

    comments = post.comment_set.all()

    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        comment_form.instance.post = post
        reply_id = request.POST.get('comment_id')
        if reply_id:
            comment_qs = Comment.objects.get(id=reply_id)
            comment_form.instance.reply = comment_qs
        comment_form.instance.author = request.user
        if comment_form.is_valid():
            comment_form.save()
            messages.success(request, f'评论已提交。')
            return redirect(f'/post/{pk}')

    else:
        comment_form = CommentForm()

    return render(request, template_name, {'object': post,
                                           'comments': comments,
                                           'comment_form': comment_form})

def book_detail(request, pk):
    template_name = 'blog/book_detail.html'
    book = get_object_or_404(Book, pk=pk)
    like1 = get_object_or_404(Book, pk=randint(5, 250))
    like2 = get_object_or_404(Book, pk=randint(4, 250))
    like3 = get_object_or_404(Book, pk=randint(7, 250))
    like4 = get_object_or_404(Book, pk=randint(6, 250))
    return render(request, template_name, {'object': book,
                                           'like1': like1,
                                           'like2': like2,
                                           'like3': like3,
                                           'like4': like4,
                                           })

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block title %} - 关于我们 {% endblock%}
{% block content %}
    <h1> 关于我们 </h1>
    <h3>该项目由西藏民族大学KNN团队开发</h3>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

    <title>藏汉图书推荐系统 {% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="https://ilmao.xyz/images/favicon.jpg">
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">བོད་རྒྱ་འི་དཔེ་དེབ་འོས་སྦྱོར་བྱེད་པའི་མ་ལག། </a>
<!--            <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">名字还没想好</a>-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog-home' %}">主页</a>
              <a class="nav-item nav-link" href="{% url 'blog-about' %}">关于</a>
            </div>

            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'blog-search' %}">图书搜索</a>
                <a class="nav-item nav-link" href="{% url 'post-create' %}">发布推荐</a>
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">个人中心</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">注销</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">登录</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">注册</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">

      <div class="row">
        <div class="col-md-9">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-3">
          <div class="content-section">
            <h3>今日推荐</h3>
            <p class='text-muted'>《当呼吸化为空气》
              <ul class="list-group">
                <li class="list-group-item list-group-item-light" >作者: [美] 保罗·卡拉尼什</li>
                <li class="list-group-item list-group-item-light">出版社: 猫头鹰文化·浙江文艺出版社</li>
                <li class="list-group-item list-group-item-light">描述:
					你在死亡中探究生命的意义，你见证生前的呼吸化作死后的空气
				</li>
              </ul>
          </div>
        </div>
      </div>
    </main>


     <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/book_detail.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block title %}- {{ object.title }}{% endblock%}
{% block content %}
<!--    这是图书信息-->
<article class="media content-section">

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="text-center" style="margin: 25px 5px 0 0">
                      <img src="{{ object.image.url }}" class="rounded" alt="Book Image">
                </div>
            </div>
            <div class="col-md-6">
                <br/>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>书名:</strong> {{ object.title }}</li>
                        <li class="list-group-item"><strong>作者:</strong> {{ object.author }}</li>
                        <li class="list-group-item"><strong>出版社:</strong> <br/><br/>{{ object.publisher }}</li>
                        <li class="list-group-item"><strong>相关链接:</strong> <br/><br/>{{ object.url }}</li>
                    </ul>
                <br/>
            </div>


            <div class="col-md-12">
                <br/>
                <hr/>
                <h5 class="article-title">描述</h5>
                <p class="article-content">{{ object.content|safe }}</p>

                <br/>
                <!-- 推荐图书 -->
                <hr/>
                <h5 class="article-title">猜你喜欢</h5>
                <br/>
                <article class="media content-section">
                    <a class="article-title" href="{% url 'book-detail' like1.id %}">{{ like1.title }}</a>
                </article>
				<article class="media content-section">
                    <a class="article-title" href="{% url 'book-detail' like2.id %}">{{ like2.title }}</a>
                </article>
				<article class="media content-section">
                    <a class="article-title" href="{% url 'book-detail' like3.id %}">{{ like3.title }}</a>
                </article>
				<article class="media content-section">
                    <a class="article-title" href="{% url 'book-detail' like4.id %}">{{ like4.title }}</a>
                </article>
            </div>
        </div>
    </div>
</article>
{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <a href="{% url 'user-posts' post.author.username %}"><img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}"></a>
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}" style="color:black">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.get_content|safe }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">首页</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">上一页</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">下一页</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">页尾</a>
      {% endif %}

    {% endif %}
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">删除文章</legend>
                <h2>确定删除 "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">确认</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">取消</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <article class="media content-section">
    <a href="{% url 'user-posts' object.author.username %}"><img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}"></a>
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'user-posts' object.author.username %}" style="color:black">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted }}</small>
        {% if object.author == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">编辑</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">删除</a>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content">{{ object.content|safe }}</p>
    </div>
  </article>



{% if user.is_authenticated %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">评论</legend>
                <div id="div_id_body" class="form-group">
                    <label for="id_body" class=" requiredField"></label>
                    <textarea name="body" class="form-control" rows="3" required id="id_body"></textarea>
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">提交</button>
            </div>
        </form>
    </div>

{% else %}
  <p>请先<a href="{% url 'login' %}?next={% url 'post-detail' object.pk %}">登录</a>后方可评论.</p>
{% endif %}


<article class="media content-section">
      <div class="card-body">
        <!-- comments -->
        <legend class="border-bottom mb-4">{{ comments.count }} 条评论 </legend>

        {% for comment in comments %}
          {% if not comment.reply %}
       <div class="media mb-4">
          <img class="rounded-circle article-img" src="{{ comment.author.profile.image.url }}" alt="" style="height: 50px; width: 50px;">
          <div class="media-body">

            <p class="font-weight-bold" href="{% url 'user-posts' comment.author.username %}">
                <a href="{% url 'user-posts' comment.author.username %}" style="color:black">{{ comment.author.username }}</a>
                <span class=" text-muted font-weight-normal">
                  {{ comment.created_on }}
                    {% if user.is_authenticated %}
                    <a class="" data-toggle="collapse" href="#collapseExample_{{ comment.id }}" role="button" aria-expanded="false" aria-controls="collapseExample">
                        回复
                    </a>
                    {% endif %}
                </span>
            </p>
            {{ comment.body | linebreaks }}

			  <div class="collapse" id="collapseExample_{{ comment.id }}">
				  <div class="container my-3">
					<form method="POST">
						{% csrf_token %}
						<input type="hidden" name="comment_id" value="{{ comment.id }}">
						<fieldset class="form-group">
							<legend class="border-bottom mb-4">评论</legend>
							<div id="div_id_body" class="form-group">
								<label for="id_body" class=" requiredField"></label>
								<textarea name="body" class="form-control" rows="3" required id="id_body"></textarea>
							</div>
						</fieldset>
						<div class="form-group">
							<button class="btn btn-outline-info" type="submit">提交</button>
						</div>
					</form>
				</div>
			  </div>



			  {% for reply in comment.replies.all %}
                <div class="media mt-4">
			  	<img class="rounded-circle article-img" src="{{ reply.author.profile.image.url }}" alt="" style="height: 50px; width: 50px;">
                  <div class="media-body">
                    <p class="font-weight-bold" href="{% url 'user-posts' comment.author.username %}">
                        <a href="{% url 'user-posts' reply.author.username %}" style="color:black">{{ reply.author.username }}</a>
                        <span class=" text-muted font-weight-normal">
                          {{ reply.created_on }}
                        </span>
                        {{ reply.body | linebreaks }}
                    </p>
                  </div>
              </div>
              {% endfor %}

          </div>
        </div>

	  {% endif %}
	{% endfor %}
  </div>
</article>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <br/>
                <legend class="border-bottom mb-4">推荐文档</legend>
                <br/>
                {{ form.media }}
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">发布</button>
            </div>
        </form>

{% endblock content %}

blog/templates/blog/search.html
{% extends "blog/base.html" %}
{% block content %}

    <form class="navbar-form navbar-left" method="get">
        <div class="form-group">
            {% csrf_token %}
            <input type="text" name="q" data-toggle="popover" class="form-control" value="{{ request.GET.q }}" placeholder="你感兴趣的图书或者作者……">
        </div>
        <button type="submit" class="btn btn-default">搜 索</button>
    </form>
    <br/>


    {% for object in object_list %}
        <article class="media content-section">
            <a class="article-title" href="{% url 'book-detail' object.id %}">{{ object.title }}</a>
        </article>
    {% endfor %}

	{% if request.GET.q %}
		{% if is_paginated %}

		  {% if page_obj.has_previous %}
			<a class="btn btn-outline-info mb-4" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">首页</a>
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">上一页</a>
		  {% endif %}

		  {% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
			  <a class="btn btn-info mb-4" href="?page={{ num }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ num }}</a>
			{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
			  <a class="btn btn-outline-info mb-4" href="?page={{ num }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ num }}</a>
			{% endif %}
		  {% endfor %}

		  {% if page_obj.has_next %}
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">下一页</a>
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">页尾</a>
		  {% endif %}

		{% endif %}
	{% endif %}

{% endblock content %}

blog/templates/blog/search_copy.html
{% extends "blog/base.html" %}
{% block content %}


<form class="navbar-form navbar-left" method="get">
        <div class="form-group">
            {% csrf_token %}
            <input type="text" name="q" data-toggle="popover" class="form-control" value="{{ request.GET.q }}" placeholder="你感兴趣的图书或者作者……">
        </div>
        <button type="submit" class="btn btn-default">搜 索</button>
    </form>
    <br/>

    <br/>

    {% for book in books %}
        <article class="media content-section">

          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ book.author.id }}</a>
              <small class="text-muted">{{ book.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ book.title }}</a></h2>
          </div>
        </article>
    {% endfor %}

	{% if books.has_other_pages %}

	  {% if books.has_previous %}
		<a class="btn btn-outline-info mb-4" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">首页</a>
		<a class="btn btn-outline-info mb-4" href="?page={{ books.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">上一页</a>
	  {% endif %}

	  {% for num in books.paginator.page_range %}
		{% if books.number == num %}
		  <a class="btn btn-info mb-4" href="?page={{ num }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ num }}</a>
		{% elif num > books.number|add:'-3' and num < books.number|add:'3' %}
		  <a class="btn btn-outline-info mb-4" href="?page={{ num }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ num }}</a>
		{% endif %}
	  {% endfor %}

	  {% if books.has_next %}
		<a class="btn btn-outline-info mb-4" href="?page={{ books.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">下一页</a>
		<a class="btn btn-outline-info mb-4" href="?page={{ books.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">页尾</a>
	  {% endif %}

	{% endif %}

{% endblock content %}